name: "Release"

# @see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    tags:
      - v1*

jobs:
  envs:
    runs-on: ubuntu-20.04
    steps:
      ################################################################
      - name: Checkout repository
        uses: actions/checkout@v3
      ################################################################
      # The github.ref is, for example, refs/tags/v5.0.145 or refs/tags/v5.0-r8
      # Generate variables like:
      #   SRS_TAG=v5.0-r8
      #   SRS_TAG=v5.0.145
      # @see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Generate varaiables
        run: |
          SRS_TAG=$(echo ${{ github.ref }}| awk -F '/' '{print $3}')
          echo "SRS_TAG=$SRS_TAG" >> $GITHUB_ENV
          SRS_MAJOR=$(echo $SRS_TAG| cut -c 2)
          echo "SRS_MAJOR=$SRS_MAJOR" >> $GITHUB_ENV
    outputs:
      SRS_TAG: ${{ env.SRS_TAG }}
      SRS_MAJOR: ${{ env.SRS_MAJOR }}

  docker:
    needs:
      - envs
    runs-on: ubuntu-20.04
    steps:
      ################################################################
      - name: Covert output to env
        run: |
          echo "SRS_TAG=${{ needs.envs.outputs.SRS_TAG }}" >> $GITHUB_ENV
          echo "SRS_MAJOR=${{ needs.envs.outputs.SRS_MAJOR }}" >> $GITHUB_ENV
      ################################################################
      - name: Checkout repository
        uses: actions/checkout@v3
      ################################################################
      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build and push to docker registry
        run: |
          docker build -t ossrs/tea:$SRS_TAG -f Dockerfile .
          docker tag ossrs/tea:$SRS_TAG ossrs/tea:$SRS_MAJOR
          docker tag ossrs/tea:$SRS_TAG ossrs/tea:latest
      - name: Push to docker hub
        run: |
          docker push ossrs/tea:$SRS_TAG
          docker push ossrs/tea:$SRS_MAJOR
          docker push ossrs/tea:latest
    outputs:
      SRS_DOCKER_DONE: ok

  aliyun:
    needs:
      - envs
      - docker
    runs-on: ubuntu-20.04
    steps:
      ################################################################
      - name: Covert output to env
        run: |
          echo "SRS_TAG=${{ needs.envs.outputs.SRS_TAG }}" >> $GITHUB_ENV
          echo "SRS_MAJOR=${{ needs.envs.outputs.SRS_MAJOR }}" >> $GITHUB_ENV
      ################################################################
      - name: Login aliyun hub
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Copy to Aliyun registry
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ossrs/tea:${{ env.SRS_TAG }}
          dst: |
            registry.cn-hangzhou.aliyuncs.com/ossrs/tea:${{ env.SRS_TAG }}
            registry.cn-hangzhou.aliyuncs.com/ossrs/tea:${{ env.SRS_MAJOR }}
            registry.cn-hangzhou.aliyuncs.com/ossrs/tea:latest
    outputs:
      SRS_ALIYUN_DONE: ok